language: python

sudo: false

install:
  - pip install -U tox

matrix:
  include:
      - python: 3.4.4
        env: TOXENV=py34
      - python: 3.5
        env: TOXENV=py35

script:
  - tox
  - if [[ "${TRAVIS_BRANCH}" == "master" ]]; then tox -e integration; fi